package thelm.jaopca.agriculture;

import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.Mod.EventHandler;
import net.minecraftforge.fml.common.Mod.Instance;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;

@Mod(
		modid = JAOPCAAgriculture.MOD_ID,
		name = JAOPCAAgriculture.NAME,
		version = JAOPCAAgriculture.VERSION,
		dependencies = "required-after:mysticalagriculture;after:mysticalagradditions;required-before:jaopca@[1.11.2-2.1.8.88,)"
		)
public class JAOPCAAgriculture {
	public static final String MOD_ID = "jaopcaagriculture";
	public static final String NAME = "JAOPCAAgriculture";
	public static final String VERSION = "1.11.2-1.1.0.12";
	@Instance(JAOPCAAgriculture.MOD_ID)
	public static JAOPCAAgriculture core;
	public static ModMetadata metadata;

	@EventHandler
	public void firstMovement(FMLPreInitializationEvent event) {
		metadata = event.getModMetadata();
		metadata.autogenerated = false;
		metadata.version = VERSION;
		metadata.authorList.add("TheLMiffy1111");
		metadata.description = "A mod that aims to add crops for more materials to Mystical Agriculture.";

		ModuleMysticalAgriculture.register();
	}
}
